= Command Line Interface (CLI)

TIP: If you're using Truffle or Buidler, check out the new https://github.com/OpenZeppelin/openzeppelin-upgrades[Upgrades plugins] to integrate upgradeability into your existing workflow.

*Develop, deploy and operate upgradeable smart contract projects*. Support for Ethereum and every other EVM-powered blockchain.

* *Interactive commands*: Send transactions, query balances, and interact with your contracts directly from the command line, using commands like `oz send-tx`, `oz call`, `oz balance`, and `oz transfer`.
* *Deploy & upgrade your contracts*: You can develop your smart contracts iteratively, speeding up development locally, or squashing bugs in production. Run `oz deploy` to deploy your contracts, followed by `oz upgrade` any time you want to change their code.
* *Link Ethereum Packages*: Use code from contracts already deployed to the blockchain directly on your project, saving gas on deployments and managing your dependencies securely, just with an `oz link` command.
* *Bootstrap your dapp*: Jumpstart your dapp by unpacking one of our starter kits, pre-configured with OpenZeppelin Contracts, React, and Infura. Run `oz unpack` to start!

== Overview

=== Installation

[source,console]
----
$ npm install @openzeppelin/cli
----

=== Usage

All CLI commands are fully interactive: you can call them with no or incomplete arguments and they will prompt you for options as they proceed.

Below is a short list of the most used commands:

  * xref:commands.adoc#init[`oz init`]: initialize your OpenZeppelin project
  * xref:commands.adoc#compile[`oz compile`]: compile all Solidity smart contracts in your project
  * xref:commands.adoc#deploy[`oz deploy`]: deploy an upgradeable smart contract
  * xref:commands.adoc#send[`oz send-tx`]: send a transaction to a contract and execute a function
  * xref:commands.adoc#call[`oz call`]: read data from the blockchain by calling `view` and `pure` functions
  * xref:commands.adoc#upgrade[`oz upgrade`]: upgrade a deployed contract to a new version without changing the address or state
  * xref:commands.adoc#unpack[`oz unpack`]: bootstrap a project with a xref:starter-kits::index.adoc[Starter Kit]
  * xref:commands.adoc#link[`oz link`]: reuse on-chain code by to a xref:dependencies.adoc[linking to Ethereum Packages]

== Learn More

 * Head to xref:getting-started.adoc[Getting Started] to see the CLI in action by deploying and upgrading a smart contract!
 * xref:dependencies.adoc[Using Dependencies] showcases a more complex project being built, including leveraging the xref:contracts::index.adoc[OpenZeppelin Contracts] library.
 * If you are a Truffle user, go to xref:truffle.adoc[Using With Truffle] for information on using both tools on the same project.
 * Take a look at the API reference for all xref:commands.adoc[CLI commands].
 * For an overview of the internals of the CLI, you can read on the xref:contracts-architecture.adoc[Contracts Architecture] and different xref:configuration.adoc[Configuration Files].

TIP: Looking for the documentation for version 2.4 or earlier? You can find it https://docs.zeppelinos.org/versions[here].
