[[openzeppelin-sdk]]
= OpenZeppelin SDK

The OpenZeppelin SDK is a platform to develop, deploy and operate smart contract projects on Ethereum and every other EVM and eWASM-powered blockchain.

TIP: Looking for the documentation for version 2.4 or earlier? You can find it https://docs.zeppelinos.org/versions[here].

[[features]]
== Features

* *Interactive commands*: Send transactions, query balances, and interact with your contracts directly from the command line.
* *Upgrade your contracts*: You can develop your smart contracts iteratively, speeding up development locally, or squashing bugs in production.
* *Link Ethereum Packages*: Use code from contracts already deployed to the blockchain directly on your project, saving gas on deployments and managing your dependencies securely.
* *Build a (d)app*: Jumpstart your dapp by unpacking one of our starter kits, pre-configured with OpenZeppelin Contracts, OpenZeppelin SDK, React, and Infura.

[[getting-started]]
== Getting Started

Start by xref:first.adoc[deploying your first OpenZeppelin SDK project].

[[security]]
== Security

If you find a security issue, please contact us at security@openzeppelin.com. We give rewards for reported issues, according to impact and severity.

[[team]]
== Team

The OpenZeppelin SDK was started and is sponsored by https://openzeppelin.com/[the OpenZeppelin team].
