= Building a Network.js powered (d)app from scratch
In this tutorial, we will integrate OpenZeppelin Network.js from the SDK, to build a (d)app that can be used in a browser with injected Web3 e.g. using MetaMask. 

The *OpenZeppelin Network.js* is an easy to use and reliable library that provides one line access to the Web3 API.  It can be used in both React and in (vanilla) JavaScript.  It also supports the Gas Station Network.

We will use the `create-react-app` package to bootstrap a React application and use Network.js to easily set up a web3 context. 

== Setting up the environment
We begin by creating a new project and installing all dependencies.

[source,console]
----
mkdir web3-dapp && cd web3-dapp
npm init -y
npm install @openzeppelin/network
----
Make sure you have the OpenZeppelin CLI installed, as well as Ganache for running a local network.

[source,console]
----
npm install --global @openzeppelin/cli ganache-cli
----

Use the CLI to set up a new project and follow the prompts.

[source,console]
----
openzeppelin init
----

We also need an injected Web3 provider such as MetaMask installed.  Follow the instructions on the https://metamask.io/[MetaMask website] to install the browser extension.

== Creating the dapp
We will create our dapp using the `create-react-app` package, which bootstraps a simple client-side application using React.

[source,console]
----
npx create-react-app client
----

On the `client/src/App.js` file, replace `App.js` in your react project with the following code:
[source,js]
----
import React from 'react';
import './App.css';

import { useWeb3 } from '@openzeppelin/network/react';

import Web3Info from './components/Web3Info/index.js';

// const infuraProjectId = process.env.REACT_APP_INFURA_PROJECT_ID;
const infuraProjectId = '95202223388e49f48b423ea50a70e336';

function App() {

  const web3Context = useWeb3(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`);

  return (
    <div className="App">

      <div>
        <div>
          <Web3Info title="Web3 Provider" web3Context={web3Context} />
        </div>
      </div>
    </div>
  );
}

export default App;
----

In the `client/src` directory create a `components` directory.  In the `components` directory create a `Web3Info` directory.  Then create an `index.js` file in the `Web3Info` directory with the following code:
[source,js]
----
import React, { useState, useEffect, useCallback } from 'react';

export default function Web3Info(props) {
  const { web3Context } = props;
  const { networkId, networkName, accounts, providerName, lib } = web3Context;

  const [balance, setBalance] = useState(0);

  const getBalance = useCallback(async () => {
    let balance =
      accounts && accounts.length > 0 ? lib.utils.fromWei(await lib.eth.getBalance(accounts[0]), 'ether') : 'Unknown';
    setBalance(balance);
  }, [accounts, lib.eth, lib.utils]);

  useEffect(() => {
    getBalance();
  }, [accounts, getBalance, networkId]);

  const requestAuth = async web3Context => {
    try {
      await web3Context.requestAuth();
    } catch (e) {
      console.error(e);
    }
  };

  const buttonStyle = {
    color: 'blue',
    cursor: 'pointer',
  };

  const requestAccess = useCallback(() => requestAuth(web3Context), []);

  return (
    <div>
      <h3> {props.title} </h3>
      <div>Network: {networkId ? `${networkId} – ${networkName}` : 'No connection'}</div>
      <div>Your address: {accounts && accounts.length ? accounts[0] : 'Unknown'}</div>
      <div>Your ETH balance: {balance}</div>
      <div>Provider: {providerName}</div>
      {accounts && accounts.length ? (
        <div>Accounts & Signing Status: Access Granted</div>
      ) : !!networkId && providerName !== 'infura' ? (
        <div>
          <br />
          <div style={buttonStyle} onClick={requestAccess}>Request Access</div>
        </div>
      ) : (
        <div></div>
      )}
    </div>
  );
}
----

== Running the dapp
We can now fire up our dapp running `npm start` from within the `client` directory. 

Once the dapp is loaded in the browser, press `Request Access` to request access to injected Web3.  

NOTE: Best practice is to wait to request web3 access until a user wants to perform an action that they can only do with Web3.

`OpenZeppelin Network.js` will re-render components on account, network, and connection changes.
Try changing networks in MetaMask and the dapp will update with the network ID and network name.  
Also try changing accounts in MetaMask and the dapp will update the address and balance.  

In this example we used `useWeb3` which attempts to obtain an injected Web3 provider (e.g. MetaMask) first, before falling back to a network connection, in this case Infura.  Instead of `useWeb3` we could `useWeb3Injected` for an injected Web3 provider or `useWeb3Network` for a network provider e.g. Infura or a private node.  Also dapps can be configured to use multiple providers if necessary.

== Gas Station Network
`OpenZeppelin Network.js` can be used with the Gas Station Network (GSN).  The example below uses a network provider (Infura), and generates an ephemeral key for signing relay requests to the GSN.
[source,js]
----
const web3Context = useWeb3Network(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`, { 
  gsn: { signKey: useEphemeralKey() } 
});
----

To get started quickly with OpenZeppelin Network.js and the Gas Station Network you can use the https://docs.openzeppelin.com/starter-kits/2.3/gsnkit[OpenZeppelin GSN Starter Kit].

To unpack the starter kit, run the following inside an empty project directory and follow the instructions.

[source,console]
----
openzeppelin unpack @openzeppelin/starter-kit-gsn
----

== (vanilla) JavaScript and non-React frameworks
`OpenZeppelin Network.js` can be used with (vanilla) JavaScript.


