= Network.js

The *OpenZeppelin Network.js* is an easy to use and reliable library that provides one line access to the Web3 API.  It can be used in both React and in (vanilla) JavaScript.

== Features

* *Abstraction*: Hides various Web3 providers behind a common API.
* *One line access*: Access Web3 providers with a single line (MetaMask, Infura, Geth, Portis etc).
* *Multiple providers*: Supports multiple Web3 providers within the same app.
* *Meta Transactions*: First class support of Gas Station Network meta-transactions.
* *React hooks*: React integration using hooks.
* *Events*: Fires events even for HTTP and forcefully terminated providers.
* *Changed events*: Network, accounts, and connection changed events for all web3 providers.

== Starter Kits
Network.js is used in the https://docs.openzeppelin.com/starter-kits/2.3/gsnkit[OpenZeppelin GSN Starter Kit] so you can start working quickly on your dapp.

To unpack the starter kit, run the following inside an empty project directory and follow the instructions.

[source,console]
----
openzeppelin unpack OpenZeppelin/starter-kit-gsn
----

== Install
To install OpenZeppelin Network.js, run the following in your projects root directory:

[source,console]
----
npm install @openzeppelin/network
----

== Usage - React
Import Network.js for React:

[source,js]
----
import { useWeb3Injected, useWeb3Network, useEphemeralKey } from '@openzeppelin/network/react';
----

You can get the Web3Context from:

* `useWeb3Injected` for an injected provider such as MetaMask.
* `useWeb3Network` for a network provider with a connection string such as Infura or a private node.
* `useWeb3` for an injected provider with a fallback to a network provider when there is no injected provider.

[source,js]
----
const web3Context = useWeb3Injected();
----
[source,js]
----
const web3Context = useWeb3Network(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`);
----
[source,js]
----
const web3Context = useWeb3(fallbackConnection: `wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`);
----
Once you have a Web3Context you can access the following:

* `accounts` of the web3 provider.  If the array is empty then accounts are either locked or not available.
* `networkId` of the current network e.g. 3 for Ropsten.
* `networkName` of the current network e.g. Ropsten.
* `providerName` of the current web3 provider e.g. metamask, infura.
* `lib` is the initialized instance of `web3.js`.
* `connected` indicates if the underlying web3 provider is available or not.

Network.js in React will re-render on changes to the above.

[source,js]
----
const { accounts, networkId, networkName, providerName, lib, connected } = web3Context;
----

== Usage - Javascript

Import Network.js for (vanilla) JavaScript:

[source,js]
----
import { fromInjected, fromConnection } from '@openzeppelin/network';
----

You can get the Web3Context from:  

* `fromInjected` for an injected provider such as MetaMask.
* `fromConnection` for a network provider with a connection string such as Infura or a private node.

[source,js]
----
const web3Context = await fromInjected();
----

[source,js]
----
const web3Context = await fromConnection('http://127.0.0.1:8545');
----

Once you have a Web3Context you can access the following:    

* `accounts` of the web3 provider.  If the array is empty then accounts are either locked or not available.
* `networkId` of the current network e.g. 3 for Ropsten.
* `networkName` of the current network e.g. Ropsten.
* `providerName` of the current web3 provider e.g. metamask, infura.
* `lib` is the initialized instance of `web3.js`.
* `connected` indicates if the underlying web3 provider is available or not.

[source,js]
----
const { accounts, networkId, networkName, providerName, lib, connected } = web3Context;
----

To get notified of changes such as `networkId`, `accounts` or `connected` changing you can subscribe to events:

[source,js]
----
function updateNetwork(networkId, networkName) {}
function updateAccounts(accounts) {}
function updateConnection(connected) {}

web3Context.on(Web3Context.NetworkIdChangedEventName, updateNetwork);
web3Context.on(Web3Context.AccountsChangedEventName, updateAccounts);
web3Context.on(Web3Context.ConnectionChangedEventName, updateConnection);
----

You should unsubscribe from events once you no longer need them:

[source,js]
----
web3Context.off(Web3Context.NetworkIdChangedEventName, updateNetwork);
web3Context.off(Web3Context.AccountsChangedEventName, updateAccounts);
web3Context.off(Web3Context.ConnectionChangedEventName, updateConnection);
----

== GSN

To use GSN, specify GSN as an option, providing a signing key:
[source,js]
----
const web3Context = useWeb3Network(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`, { 
  gsn: { signKey: useEphemeralKey() } 
});
----

In a local development environment you can pass a `dev: true` flag to the gsn options so a relayer is not required.

[source,js]
----
const web3Context = useWeb3Network('http://127.0.0.1:8545', { 
  gsn: { 
    dev: true,
    signKey: useEphemeralKey() 
  } 
});
----
