= Network.js

The *OpenZeppelin Network.js* is an easy to use and reliable library that provides one line access to the Web3 API.  It can be used in both React and in vanilla JavaScript.

== Features

* *Abstraction*: Hides various Web3 providers behind a common API.
* *One line access*: Access Web3 providers with a single line (MetaMask, Infura, Geth, Portis etc).
* *Multiple providers*: Supports multiple Web3 providers within the same app.
* *Meta Transactions*: First class support of Gas Station Network meta-transactions.
* *React hooks*: React integration using hooks.
* *Events*: Fires events even for HTTP and forcefully terminated providers.
* *Changed events*: Network, accounts, and connection changed events for all web3 providers.

== Install
To install OpenZeppelin Network.js, run the following in your projects root directory:

[source,console]
----
npm install @openzeppelin/network
----

== Starter Kits
Network.js is used in the OpenZeppelin GSN Starter Kit so you can start working quickly on your dapp.

To unpack the starter kit, run the following inside an empty project directory and follow the instructions.

[source,console]
----
openzeppelin unpack OpenZeppelin/starter-kit-gsn
----

== Usage - React
Import Network.js for React:

[source,js]
----
import { useWeb3Injected, useWeb3Network, useEphemeralKey } from '@openzeppelin/network/react';
----

You can get the Web3Context from an injected provider such as MetaMask or use a network provider such as Infura:

[source,js]
----
const web3Context = useWeb3Injected();
----
[source,js]
----
const web3Context = useWeb3Network(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`);
----

Once you have a web3Context you can get fresh data.  Network.js will re-render the component when network, accounts or connection state change.

Web3 library can be accessed via `lib`

[source,js]
----
const { accounts, networkId, networkName, providerName, lib, connected } = web3Context;
----

== Usage - Javascript

Import Network.js for (vanilla) JavaScript:

[source,js]
----
import { fromInjected, fromConnection } from '@openzeppelin/network';
----

You can get the Web3Context from an injected provider such as MetaMask or use a network provider such as Infura:
[source,js]
----
const web3Context = await fromInjected();
----

[source,js]
----
const web3Context = await fromConnection('http://127.0.0.1:8545');
----

Once you have a web3Context you can access data.  
Web3 library can be accessed via `lib`

[source,js]
----
const { accounts, networkId, networkName, providerName, lib, connected } = web3Context;
----

To get notified of events such as `networkId`, `accounts` or `connected` status changing you can subscribe to events:
[source,js]
----
function updateNetwork(networkId, networkName) {}
function updateAccounts(accounts) {}
function updateConnection(connected) {}

web3Context.on(Web3Context.NetworkIdChangedEventName, updateNetwork);
web3Context.on(Web3Context.AccountsChangedEventName, updateAccounts);
web3Context.on(Web3Context.ConnectionChangedEventName, updateConnection);
----

You should unsubscribe from events once you no longer need them:

[source,js]
----
web3Context.off(Web3Context.NetworkIdChangedEventName, updateNetwork);
web3Context.off(Web3Context.AccountsChangedEventName, updateAccounts);
web3Context.off(Web3Context.ConnectionChangedEventName, updateConnection);
----

== GSN

To use GSN, specify GSN as an option, providing a signing key:
[source,js]
----
const web3Context = useWeb3Network(`wss://rinkeby.infura.io/ws/v3/${infuraProjectId}`, { 
  gsn: { signKey: useEphemeralKey() } 
});
----

In a local development environment you can pass a `dev: true` flag to the gsn options so a relayer is not required.

[source,js]
----
const web3Context = useWeb3Network('http://127.0.0.1:8545', { 
  gsn: { 
    dev: true,
    signKey: useEphemeralKey() 
  } 
});
----
