= Building a Network.js powered (d)app from scratch
In this tutorial, we will integrate OpenZeppelin Network.js from the SDK, to build a (d)app. 

The *OpenZeppelin Network.js* is an easy to use and reliable library that provides one line access to the Web3 API.  It can be used in both React and in (vanilla) JavaScript.

We will use the create-react-app package to bootstrap a React application and use Network.js to easily set up a web3 object. 

== Setting up the environment
We will begin by creating a new project and installing all dependencies.

[source,console]
----
mkdir web3-dapp && cd web3-dapp
npm init -y
npm install @openzeppelin/network
----
Make sure you have the OpenZeppelin CLI installed, as well as Ganache for running a local network.

[source,console]
----
npm install --global @openzeppelin/cli ganache-cli
----

Use the CLI to set up a new project and follow the prompts.

[source,console]
----
openzeppelin init
----

== Creating the dapp
We will create our (d)app using the `create-react-app` package, which bootstraps a simple client-side application using React.

[source,console]
----
npx create-react-app client
----

On the `client/src/App.js` file, replace `App.js` in your react project with the following code:
[source,js]
----
import React from 'react';
import './App.css';

import { useWeb3Injected } from '@openzeppelin/network/react';

import Web3Info from './components/Web3Info/index.js';

function App() {

  const context = useWeb3Injected();

  return (
    <div className="App">

      <div>
        <div>
          <Web3Info title="Web3 Provider" context={context} />
        </div>
      </div>
    </div>
  );
}

export default App;
----

In the `src` directory create a `components` directory and in `components` create a `Web3Info` directory.  Create an `index.js` file in `Web3Info` directory with the following code:
[source,js]
----
import React, { useState, useEffect, useCallback } from 'react';

export default function Web3Info(props) {
  const { context } = props;
  const { networkId, networkName, accounts, providerName, lib } = context;

  const [balance, setBalance] = useState(0);

  const getBalance = useCallback(async () => {
    let balance =
      accounts && accounts.length > 0 ? lib.utils.fromWei(await lib.eth.getBalance(accounts[0]), 'ether') : 'Unknown';
    setBalance(balance);
  }, [accounts, lib.eth, lib.utils]);

  useEffect(() => {
    getBalance();
  }, [accounts, getBalance, networkId]);

  const requestAuth = async web3Context => {
    try {
      await web3Context.requestAuth();
    } catch (e) {
      console.error(e);
    }
  };

  const buttonStyle = {
    color: 'blue',
    cursor: 'pointer',
  };

  return (
    <div>
      <h3> {props.title} </h3>
      <div>
        Network: {networkId ? `${networkId} – ${networkName}` : 'No connection'}
      </div>
      <div>
        Your address: {accounts && accounts.length ? accounts[0] : 'Unknown'}
      </div>
      <div>
        Your ETH balance: {balance}
      </div>
      <div>
        Provider: {providerName}
      </div>
      {accounts && accounts.length ? (
        <div>
          Accounts & Signing Status: Access Granted
        </div>
      ) : !!networkId && providerName !== 'infura' ? (
        <div>
          <br />
          <div style={buttonStyle} onClick={() => requestAuth(context)}>Request Access</div>
        </div>
      ) : (
        <div></div>
      )}
    </div>
  );
}
----

== Starter Kits
Network.js is used in the https://docs.openzeppelin.com/starter-kits/2.3/gsnkit[OpenZeppelin GSN Starter Kit] so you can start working quickly on your dapp.

To unpack the starter kit, run the following inside an empty project directory and follow the instructions.

[source,console]
----
openzeppelin unpack OpenZeppelin/starter-kit-gsn
----


