[[testing-upgradeable-projects]]
= Testing upgradeable projects

When working with the OpenZeppelin SDK, you can test your contracts as you usually do. That is, you can manually deploy your logic contracts, and test them just like any other contract. However, when using the OpenZeppelin SDK, you are dealing with upgradeable instances. Of course, you could use the OpenZeppelin SDK at a lower level programmatically in your tests but this could be rather cumbersome.

Instead, you can use specifically designed OpenZeppelin SDK tools that automatically set up your entire project in your testing environment. This allows you to replicate the same set of contracts that manage your project for each test you run.

The `@openzeppelin/cli` package provides a `TestHelper()` function to retrieve your project structure from the `.openzeppelin/project.json` file and deploy everything to the current test network. All the contracts that you have registered via `openzeppelin add`, plus all the contracts provided by the Ethereum Packages you have linked, will be available. The returned project object (either a https://github.com/OpenZeppelin/openzeppelin-sdk/blob/v2.2.0/packages/lib/src/project/ProxyAdminProject.ts[`ProxyAdminProject`] or an https://github.com/OpenZeppelin/openzeppelin-sdk/blob/v2.2.0/packages/lib/src/project/AppProject.ts[`AppProject`]) provides convenient methods for creating upgradeable instances of your contracts, which you can use within your tests. Let's see how this would work in a simple project.

[[setting-up-a-sample-project]]
== Setting up a sample project

The following section describes a succinct way in how a simple OpenZeppelin SDK project can be set up. If you already have a project set up, you may skip to the next section.

_If you don't understand what's going on in this section, please refer to the Quickstart guides of the documentation, specifically the xref:deploying.adoc[Deploying your first project], xref:upgrading.adoc[Upgrading your project] and xref:linking.adoc[Linking to Ethereum Packages] guides. These guides provide detailed explanations on how a basic OpenZeppelin SDK project works._

Create a new project by running:

[source,console]
----
mkdir my-project
cd my-project
npm init --yes
npm install @openzeppelin/cli @openzeppelin/upgrades @openzeppelin/contracts-ethereum-package truffle chai
----

Now, run:

[source,console]
----
npx openzeppelin init my-project
----

Let's add a simple contract to the project, create the file `contracts/Sample.sol`:

[source,solidity]
----
pragma solidity ^0.5.0;

contract Sample {
  function greet() public pure returns (string memory) {
    return "A sample";
  }
}
----

Now, add your contract to your OpenZeppelin SDK project:

[source,console]
----
npx openzeppelin add Sample
----

And link your OpenZeppelin SDK project to the `@openzeppelin/contracts-ethereum-package` Ethereum Package:

[source,console]
----
npx openzeppelin link @openzeppelin/contracts-ethereum-package
----

[[writing-the-test-script]]
== Writing the test script

TIP: This test is written in ES5 Javascript. If you'd like to use ES6 syntax instead, make sure you xref:faq.adoc#how-do-i-use-es6-javascript-syntax-in-my-tests[set up babel in your project].

Now, let's create the test file `test/Sample.test.js`:

[source,javascript]
----
const { TestHelper } = require('@openzeppelin/cli');
const { Contracts, ZWeb3 } = require('@openzeppelin/upgrades');

ZWeb3.initialize(web3.currentProvider);

const Sample = Contracts.getFromLocal('Sample');
const ERC20 = Contracts.getFromNodeModules('@openzeppelin/contracts-ethereum-package', 'ERC20');

require('chai').should();

contract('Sample', function () {

  beforeEach(async function () {
    this.project = await TestHelper();
  })

  it('should create a proxy', async function () {
    const proxy = await this.project.createProxy(Sample);
    const result = await proxy.methods.greet().call();
    result.should.eq('A sample');
  })

  it('should create a proxy for the Ethereum Package', async function () {
    const proxy = await this.project.createProxy(ERC20, { contractName: 'StandaloneERC20', packageName: '@openzeppelin/contracts-ethereum-package' });
    const result = await proxy.methods.totalSupply().call();
    result.should.eq('0');
  })
})
----

Next, modify your `package.json` file to include the following script:

[source,json]
----
"test": "truffle test"
----

And run the test in your console with:

[source,console]
----
npm test
----

That's it! Now, let's look at what we just did in more detail.

[[understanding-the-test-script]]
== Understanding the test script

We first require `TestHelper` from `@openzeppelin/cli`. This helper facilitates the creation of a project object that will set up the entire OpenZeppelin SDK project within a test environment.

[source,js]
----
const { TestHelper } = require('@openzeppelin/cli');
----

We are also requiring `Contracts` and `ZWeb3` from `@openzeppelin/upgrades`. `Contracts` helps us retrieve compiled contract artifacts, while `ZWeb3` is needed to set up our Web3 provider in the OpenZeppelin SDK.

[source,js]
----
const { Contracts, ZWeb3 } = require('@openzeppelin/upgrades');

ZWeb3.initialize(web3.currentProvider);

const Sample = Contracts.getFromLocal('Sample');
const ERC20 = Contracts.getFromNodeModules('@openzeppelin/contracts-ethereum-package', 'ERC20');
----

We then invoke `TestHelper` in the test, optionally including a set of options to be used when deploying the contracts (such as `from`, `gas`, and `gasPrice`):

[source,js]
----
beforeEach(async function () {
  this.project = await TestHelper()
});
----

And finally, we add the tests themselves. Notice how each test first creates a upgradeable instance for each contract:

[source,js]
----
const proxy = await this.project.createProxy(Sample);
----

The https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/src/project/BaseSimpleProject.ts#L96[createProxy] method of the project accepts an additional object parameter in which you can specify an initializer function with arguments, just as you would by using the regular `openzeppelin create` command from the CLI, but due to the simplicity of this example, it's not necessary in our case. If you would need to pass parameters though, you would do so like this:

[source,js]
----
const proxy = await this.project.createProxy(Sample, {
  initMethod: 'initialize',
  initArgs: [42]
});
----

This is assuming our `Sample` contract had an `initialize` function with one `uint256` parameter, which it doesn't. The above code simply illustrates how you would create the upgradeable instance if it had an `initialize` function.

Continuing with our example, notice that the way we interact with the contracts is by using their `methods` object. This is because the OpenZeppelin SDK uses the web3.js 1.0 Contract interface:

[source,js]
----
const result = await proxy.methods.totalSupply().call();
----

This is how you should write tests for your OpenZeppelin SDK projects. The project object provided by `TestHelper` wraps all of the OpenZeppelin SDK programmatic interface in a way that is very convenient to use in tests. By running tests in this way, you make sure that you are testing your contracts with the exact set of conditions that they would have in production, after you deploy them with the OpenZeppelin SDK.

[[calling-initialize-functions-manually-in-your-tests]]
== Calling initialize functions manually in your tests

Sometimes, there are situations where a contract has functions that have matching names, but different arities. Here's an example of a `TimedCrowdsale` contract that inherits from `Crowdsale` which results in a contract that has two `initialize` functions with different arities:

[source,solidity]
----
contract TimedCrowdsale is Crowdsale {

  initialize(uint256 _openingTime, uint256 _closingTime) public initializer {
    Crowdsale.initialize(_rate, _wallet, _token);
  }
}

contract Crowdsale {

  initialize(uint256 _rate, address _wallet, ERC20 _token) public initializer {
    // does something
  }
}
----

This means that calls to contracts with more than one function named `initialize`, as is the case with some contracts from OpenZeppelin (e.g., `TimedCrowdsale`), may revert if you call `initialize` directly from Truffle. `openzeppelin create` handles this correctly as it encodes the parameters. However, for your unit tests you will need to call `initialize` manually.

As of version 5, Truffle has the ability to overcome the problem depicted above. That is, you can call functions with matching names that have different arities in Javascript by using the methods property of Truffle Contract.

To call TimedCrowdsale's initialize function, use the following syntax:

[source,javascript]
----
timedCrowadsale.methods['initialize(uint256,uint256)'](openingTime, closingTime);
----

And to call Crowdsale's initialize function,

[source,javascript]
----
timedCrowadsale.methods['initialize(uint256,address,address)'](rate, wallet, token);
----
