[[starter-kit]]
= Starter Kit

The OpenZeppelin Starter Kit allows you to bootstrap your decentralized application. It optionally includes an interactive tutorial to help you take your first steps in the world of smart contract development.

[[how-it-works]]
== How it works

The starter kit works by creating a React application that serves a web user interface. This interface allows you to interact with your smart contracts via a web3 provider: Metamask, Coinbase Wallet. The interaction is enabled by Truffle and the OpenZeppelin SDK. They work together to compile and test your smart contracts locally. Eventually, you need to take your application to mainnet, and Infura is already configured to help you do so effortlessly.

[[features]]
== Features

* Upgrade smart contracts. Fix bugs and security vulnerabilities, and introduce new features to your projects without migrating all your data.
* Reuse on-chain code. Reuse on-chain Solidity code that has been vetted by the community. Link to on-chain smart contract packages (Ethereum Packages) as building blocks for your project, and publish your packages for others to use. OpenZeppelin is included in the example.
* Easily connect with Ethereum networks via preconfigured Infura API keys. Use Infura to connect and access data from different test-nets and mainnet of Ethereum. They provide an easy-to-use API and developer tools to enable secure, reliable, and scalable access to Ethereum and IPFS (InterPlanetary File System).
* Compile and test smart contracts. The Starter Kit includes the Truffle suite that contains a development environment, testing framework, and asset pipeline for blockchains using the Ethereum Virtual Machine (EVM).
* Create adaptable and responsive UI components. The Starter Kit includes React and Rimble to give you all the components and flexibility you need to build responsive user interfaces.

[[getting-started]]
== Getting Started

Visit the Starter Kit https://openzeppelin.com/start[website] and follow the instructions.
